name: Generate Commit Messages
on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Create-Commit-Message:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Fetch PR diff
      run: |
        # Fetch all branches
        git fetch --all
        
        # Ensure the base branch (main or another) is available
        git checkout main || git checkout master
        
        # Fetch the PR diff
        git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
        
        # Compare the PR branch with the base branch (adjust 'main' if needed)
        git diff origin/main..pr-branch > pr_diff.patch
        # Debug: Check if diff file has content
        cat pr_diff.patch
    
    - name: Run Python script with PR diff as input
      run: |
        python3 Test.py pr_diff.patch
