name: Generate Commit Messages
on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Create-Commit-Message:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Fetch PR diff
      run: |
        # Get the base and head branch names
        BASE_BRANCH=${{ github.event.pull_request.base.ref }}
        HEAD_BRANCH=${{ github.event.pull_request.head.ref }}
        
        # Fetch the base branch
        git fetch origin $BASE_BRANCH
        
        # Compare the base branch with the current checked-out branch (HEAD)
        git diff origin/$BASE_BRANCH..$HEAD_BRANCH > pr_diff.patch
        
        # Debug: Output base and head branch info, and the diff content
        echo "Base branch: $BASE_BRANCH"
        echo "Head branch: $HEAD_BRANCH"
        cat pr_diff.patch
    
    - name: Run Python script with PR diff as input
      run: |
        python3 Test.py pr_diff.patch
